#pragma once

#define I2C_PORT i2c0
#define I2C_SDA 16
#define I2C_SCL 17
#define RESET_BTN_PIN 22

#define SCAN_INTERVAL_MS 20
#define LED_UPDATE_INTERVAL_MS 50
#define LED_FLASH_INTERVAL_MS 200

// Reset button
#define RESET_BUTTON_SCAN_INTERVAL_MS 25
#define RESET_BUTTON_PRESS_MS 10
#define RESET_BUTTON_HOLD_STAGE_1_MS 1000
#define RESET_BUTTON_HOLD_STAGE_2_MS 2500